# Generated by Django 5.1.1 on 2024-11-06 22:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0003_remove_menu_menu_item_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='menu',
            name='menu_item_description',
            field=models.TextField(default=' ', max_length=1000),
        ),
    ]
